import { Metadata } from "next";
import "./globals.css";

import styles from './layout.module.css'
import Head from "next/head";

export const metadata: Metadata = {
  // title: "Create Next App",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru" className={styles.layout}>
      <Head>
        {/* TODO (2024.03.12): Check @next/next/no-page-custom-font */}
        {/* TODO (2024.03.12): Download font locally */}
        <link 
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200&display=optional" 
          rel="stylesheet" 
        />
      </Head>

      <body className={styles.container}>
        <header className={styles.header}>
          {/* logo */}
          {/* logo text */}

          {/* checkout button */}
        </header>

        <main className={styles.content}>
          {children}
        </main>

        <footer className={styles.footer}>
        </footer>
      </body>
    </html>
  );
}
